#!/usr/bin/env python3
"""Give a brain a local website.

Copies the page into <repo>/site/, the builder into <repo>/scripts/, and builds
the brain's data.json. Then tells you how to look at it.

The page is model-driven: tabs, cards, charts, filters and the knowledge graph
all come from SCHEMA.yml, so a brain with entity types this page has never seen
gets a working UI. A brain that does not declare a model does not get a page —
see build_site.py for why that is a refusal rather than a guess.

**This produces a local preview.** It writes no workflow and publishes nothing.
A brain is private; which of its fields must never leave it differs per brain,
and getting that wrong is not recoverable. Publishing is a separate, deliberate
act — see the skill's "Give a brain a website" section.

Usage:
    add_site.py <brain-repo>
    add_site.py <brain-repo> --force     overwrite a page already customised
    add_site.py <brain-repo> --check     report what it would do, write nothing
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent
PAGE_FILES = ["index.html", "style.css", "app.js"]
IGNORE_LINE = "site/data.json"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("repo", type=Path)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    repo = args.repo.resolve()

    if not (repo / "SCHEMA.yml").exists():
        print(
            f"{repo} does not declare a model (no SCHEMA.yml), so there is nothing\n"
            "for a page to render. Declare the entity types, their folders and their\n"
            "reference fields first — a brain that declares one is the worked example.\n\n"
            "The same declaration drives the validator and the rollups, so it is worth\n"
            "having whether or not the brain ever gets a website.",
            file=sys.stderr,
        )
        return 2

    plan: list[str] = []
    site = repo / "site"
    for name in PAGE_FILES:
        source, target = SKILL / "site" / name, site / name
        if not target.exists():
            plan.append(f"add site/{name}")
        elif not filecmp.cmp(source, target, shallow=False):
            plan.append(f"{'overwrite' if args.force else 'SKIP (customised)'} site/{name}")
    builder = repo / "scripts" / "build_site.py"
    if not builder.exists() or not filecmp.cmp(SKILL / "scripts" / "build_site.py", builder, shallow=False):
        plan.append("update scripts/build_site.py")

    gitignore = repo / ".gitignore"
    ignored = IGNORE_LINE in gitignore.read_text(encoding="utf-8") if gitignore.exists() else False
    if not ignored:
        plan.append(f"add {IGNORE_LINE} to .gitignore")

    if args.check:
        print("\n".join(f"  would {step}" for step in plan) or "  nothing to do")
        return 0

    site.mkdir(parents=True, exist_ok=True)
    (repo / "scripts").mkdir(parents=True, exist_ok=True)
    for name in PAGE_FILES:
        source, target = SKILL / "site" / name, site / name
        if target.exists() and not filecmp.cmp(source, target, shallow=False) and not args.force:
            print(f"  kept your site/{name} (differs; pass --force to replace it)")
            continue
        shutil.copy2(source, target)
    shutil.copy2(SKILL / "scripts" / "build_site.py", repo / "scripts" / "build_site.py")

    # data.json is generated. Committing it is how two copies of a brain start
    # disagreeing about what the brain says.
    if not ignored:
        with gitignore.open("a", encoding="utf-8") as fh:
            fh.write(f"\n# generated by scripts/build_site.py\n{IGNORE_LINE}\n")

    result = subprocess.run(
        [sys.executable, str(repo / "scripts" / "build_site.py"), str(repo)],
        capture_output=True, text=True,
    )
    sys.stdout.write(result.stdout)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return result.returncode

    print(
        f"\nLook at it:\n"
        f"  cd {repo}/site && python3 -m http.server 8777\n"
        f"  then open http://localhost:8777/\n\n"
        "Rebuild the data after changing the wiki:\n"
        f"  python3 {repo}/scripts/build_site.py {repo}\n\n"
        "This is a local preview. It publishes nothing."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
