#!/usr/bin/env python3
"""Generate the index page under each entity folder.

445 entity files are not browsable. A folder listing is alphabetical and tells
you nothing about which entries matter; these group by the axis someone
actually navigates on -- who the customer is, which sector, what stage.

Generated rather than written by hand. With several people and processes
committing, a hand-maintained index is wrong within a day, and a stale index is
worse than none because people trust it. Run this after a batch of changes, or
let CI keep it current.

This script renders the *default* entity model -- organizations, people,
projects, products -- and the axes that model navigates on. A brain that
declares its own model in SCHEMA.yml is not that model, and guessing produced
navigation that was wrong in both directions: an empty `organizations.md` for a
brain with no organizations, and no page at all for the entity types it does
have. Such a brain gets a refusal and a pointer to its own copy instead.

A folder the brain does not have gets no page, rather than a page saying zero.

Usage:
    build_rollups.py <repo>            write the rollups
    build_rollups.py <repo> --check    exit 1 if they are out of date
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    print("needs PyYAML:  pip install pyyaml", file=sys.stderr)
    raise SystemExit(2)

BANNER = "<!-- Generated by scripts/build_rollups.py — edits here will be overwritten. -->"


def load(folder: Path) -> dict[str, dict]:
    out = {}
    for path in sorted(folder.glob("*.md")):
        if path.name in {"README.md", "index.md"}:
            continue
        text = path.read_text(encoding="utf-8")
        data = {}
        if text.startswith("---"):
            try:
                data = yaml.safe_load(text.split("---", 2)[1]) or {}
            except yaml.YAMLError:
                data = {}
        out[path.stem] = data if isinstance(data, dict) else {}
    return out


def label(slug: str, entities: dict[str, dict]) -> str:
    return (entities.get(slug) or {}).get("name") or slug.replace("-", " ")


def link(folder: str, slug: str, entities: dict[str, dict]) -> str:
    return f"[{label(slug, entities)}]({folder}/{slug}.md)"


def section(title: str, rows: list[str]) -> list[str]:
    if not rows:
        return []
    return [f"\n## {title}\n", *rows]


def roll_organizations(orgs, projects) -> str:
    # How many engagements each organization is the customer on -- the single
    # most useful ordering, and not visible from a directory listing.
    counts: dict[str, int] = defaultdict(int)
    for data in projects.values():
        for org in data.get("organizations") or []:
            if isinstance(org, dict) and org.get("role") == "customer" and org.get("slug"):
                counts[org["slug"]] += 1

    by_sector: dict[str, list[str]] = defaultdict(list)
    for slug in orgs:
        by_sector[(orgs[slug].get("broad_sector") or "Unclassified")].append(slug)

    lines = [f"# Organizations\n", BANNER, f"\n{len(orgs)} organizations."]
    for sector in sorted(by_sector):
        rows = []
        for slug in sorted(by_sector[sector], key=lambda s: label(s, orgs).lower()):
            n = counts.get(slug, 0)
            suffix = f" — {n} engagement{'s' if n != 1 else ''}" if n else ""
            rows.append(f"- {link('organizations', slug, orgs)}{suffix}")
        lines += section(f"{sector} ({len(by_sector[sector])})", rows)
    return "\n".join(lines) + "\n"


def roll_projects(projects, orgs) -> str:
    by_stage: dict[str, list[str]] = defaultdict(list)
    for slug, data in projects.items():
        by_stage[(data.get("engagement_stage") or "Stage not recorded")].append(slug)

    lines = [f"# Projects\n", BANNER, f"\n{len(projects)} engagements."]
    # Production first: what shipped is what people look for.
    order = ["Production Scale", "Pilot", "POC (Proof of Concept)", "Stage not recorded"]
    for stage in order + [s for s in sorted(by_stage) if s not in order]:
        if stage not in by_stage:
            continue
        rows = []
        for slug in sorted(by_stage[stage], key=lambda s: label(s, projects).lower()):
            customers = [
                link("organizations", o["slug"], orgs)
                for o in (projects[slug].get("organizations") or [])
                if isinstance(o, dict) and o.get("role") == "customer" and o.get("slug")
            ]
            who = f" — {', '.join(customers)}" if customers else ""
            rows.append(f"- {link('projects', slug, projects)}{who}")
        lines += section(f"{stage} ({len(by_stage[stage])})", rows)
    return "\n".join(lines) + "\n"


def roll_people(people, orgs) -> str:
    by_org: dict[str, list[str]] = defaultdict(list)
    for slug, data in people.items():
        affiliations = [
            a["organization"] for a in (data.get("affiliations") or [])
            if isinstance(a, dict) and a.get("organization") and a.get("status") != "past"
        ]
        for org in affiliations or ["No current affiliation"]:
            by_org[org].append(slug)

    lines = [f"# People\n", BANNER, f"\n{len(people)} people."]
    for org in sorted(by_org, key=lambda o: (label(o, orgs) if o in orgs else o).lower()):
        heading = label(org, orgs) if org in orgs else org
        rows = []
        for slug in sorted(by_org[org], key=lambda s: label(s, people).lower()):
            roles = [
                a.get("role") for a in (people[slug].get("affiliations") or [])
                if isinstance(a, dict) and a.get("organization") == org and a.get("role")
            ]
            rows.append(f"- {link('people', slug, people)}" + (f" — {roles[0]}" if roles else ""))
        lines += section(f"{heading} ({len(by_org[org])})", rows)
    return "\n".join(lines) + "\n"


def roll_products(products, projects) -> str:
    used: dict[str, int] = defaultdict(int)
    for data in projects.values():
        for item in (data.get("products_leveraged") or []) + (data.get("reusable_components") or []):
            if isinstance(item, str):
                used[item] += 1

    lines = [f"# Products\n", BANNER,
             f"\n{len(products)} products — artifacts reused beyond the engagement that built them."]
    rows = []
    for slug in sorted(products, key=lambda s: label(s, products).lower()):
        n = used.get(slug, 0)
        bits = [b for b in [products[slug].get("license"), products[slug].get("funding_model")] if b]
        detail = f" — used in {n} engagement{'s' if n != 1 else ''}" if n else ""
        detail += f" · {' · '.join(bits)}" if bits else ""
        rows.append(f"- {link('products', slug, products)}{detail}")
    lines += section("All products", rows)
    return "\n".join(lines) + "\n"


DEFAULT_FOLDERS = ("organizations", "people", "projects", "products")


def declared_folders(repo: Path) -> set[str] | None:
    """The entity folders this brain says it has, or None if it says nothing.

    A brain with a SCHEMA.yml is describing its own entity model; CONVENTIONS.md
    alone is the default model. Read rather than assumed, because the assumption
    wrote pages for entity types a brain did not have.
    """
    schema = repo / "SCHEMA.yml"
    if not schema.is_file():
        return None
    try:
        data = yaml.safe_load(schema.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return None
    entities = data.get("entities") or {}
    if not isinstance(entities, dict):
        return None
    folders = {
        spec.get("folder")
        for spec in entities.values()
        if isinstance(spec, dict) and spec.get("folder")
    }
    return folders or None


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        return 0
    if len(args) != 1:
        print(__doc__)
        return 1
    repo = Path(args[0])

    declared = declared_folders(repo)
    if declared is not None and not declared <= set(DEFAULT_FOLDERS):
        own = repo / "scripts" / "build_rollups.py"
        print(
            f"{repo} declares its own entity model in SCHEMA.yml "
            f"({', '.join(sorted(declared))}).\n"
            "This script renders the default model only, so it would write pages for "
            "entity types\nthis brain does not have and none for the ones it does.",
            file=sys.stderr,
        )
        if own.is_file():
            print(f"\nUse the brain's own copy:  python3 {own} {repo}", file=sys.stderr)
        else:
            print(
                "\nThis brain has no scripts/build_rollups.py of its own. A schema-driven "
                "rollup\nbuilder is what it needs; a schema-driven brain has a worked "
                "example.",
                file=sys.stderr,
            )
        return 2

    orgs = load(repo / "organizations")
    people = load(repo / "people")
    projects = load(repo / "projects")
    products = load(repo / "products")

    candidates = {
        "organizations.md": ("organizations", lambda: roll_organizations(orgs, projects)),
        "projects.md": ("projects", lambda: roll_projects(projects, orgs)),
        "people.md": ("people", lambda: roll_people(people, orgs)),
        "products.md": ("products", lambda: roll_products(products, projects)),
    }
    # A rollup for a folder that is not there would be a page reading "0 items",
    # which looks like an answer and is only an assumption.
    pages = {
        name: render()
        for name, (folder, render) in candidates.items()
        if (repo / folder).is_dir()
    }
    if not pages:
        print(f"{repo} has none of the default entity folders "
              f"({', '.join(DEFAULT_FOLDERS)}) — nothing to roll up.", file=sys.stderr)
        return 2

    stale = []
    for name, content in pages.items():
        path = repo / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print("rollups are out of date: " + ", ".join(stale), file=sys.stderr)
            print("run:  python3 scripts/build_rollups.py .", file=sys.stderr)
            return 1
        print("rollups are current")
        return 0

    print(f"wrote {len(pages)} rollups")
    for name in pages:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
