#!/usr/bin/env python3
"""Generate INDEX.md — the wiki's slug and alias map, for cheap dedup.

The near-duplicate is the main degradation path a growing wiki has: the same
organization captured under two spellings, the same person under a nickname.
Checking "is this already known" used to cost reads against the wiki, so it
got skipped. INDEX.md makes the check free: one generated file holding every
slug and every alias, small enough to inject at session start.

Runs in the wiki's CI alongside build_rollups.py and build_backlinks.py —
regenerate before validation, commit the result. Also runnable by hand:

    build_index.py <wiki-root>            write INDEX.md
    build_index.py <wiki-root> --check    exit 1 if INDEX.md is stale

Reads folders from SCHEMA.yml's `entities:` where one exists, else falls back
to the conventional folders. Requires PyYAML, like the other wiki scripts.

Format, one line per entity, deliberately grep-able:

    ## organizations (197)
    - acme-corp — Acme Corporation (aka: ACME, Acme Inc)
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("build_index.py needs PyYAML (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

FALLBACK_FOLDERS = ["organizations", "people", "projects", "products"]
HEADER_NOTE = (
    "Generated by build_index.py — do not edit. One line per entity: "
    "slug, name, aliases. The point is answering \"is this already known\" "
    "without reading the wiki."
)


def entity_folders(root: Path) -> list[str]:
    schema = root / "SCHEMA.yml"
    if schema.exists():
        try:
            data = yaml.safe_load(schema.read_text()) or {}
            entities = data.get("entities") or {}
            folders = [spec.get("folder") for spec in entities.values()
                       if isinstance(spec, dict) and spec.get("folder")]
            if folders:
                return sorted(folders)
        except yaml.YAMLError:
            pass
    return [f for f in FALLBACK_FOLDERS if (root / f).is_dir()]


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    try:
        data = yaml.safe_load(text[3:end])
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def entity_line(path: Path) -> str:
    meta = frontmatter(path)
    slug = path.stem
    name = str(meta.get("name") or "").strip()
    aliases = meta.get("aliases") or meta.get("aka") or []
    if not isinstance(aliases, list):
        aliases = [aliases]
    aliases = [str(a).strip() for a in aliases if str(a).strip()]
    line = f"- {slug}"
    if name and name != slug:
        line += f" — {name}"
    if aliases:
        line += f" (aka: {', '.join(aliases)})"
    return line


def render(root: Path) -> str:
    folders = entity_folders(root)
    sections, total = [], 0
    for folder in folders:
        directory = root / folder
        if not directory.is_dir():
            continue
        files = sorted(p for p in directory.glob("*.md")
                       if p.name.lower() != "readme.md")
        if not files:
            continue
        total += len(files)
        lines = [entity_line(p) for p in files]
        sections.append(f"## {folder} ({len(files)})\n\n" + "\n".join(lines))
    # The date is the one non-deterministic byte; --check compares everything
    # below the header so a same-day regeneration is not spuriously "stale".
    head = (f"# Index\n\n{HEADER_NOTE}\n\n"
            f"{total} entities · generated {date.today().isoformat()}\n")
    return head + "\n" + "\n\n".join(sections) + "\n"


def body(text: str) -> str:
    """Everything after the generated-date line, for drift comparison."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if "generated" in line:
            return "\n".join(lines[i + 1:]).strip()
    return text.strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("root", help="wiki repository root")
    parser.add_argument("--check", action="store_true",
                        help="report staleness and exit non-zero; never write")
    args = parser.parse_args()

    root = Path(args.root)
    if not (root / "CONVENTIONS.md").exists():
        print(f"{root} does not look like a wiki (no CONVENTIONS.md)",
              file=sys.stderr)
        return 2

    fresh = render(root)
    target = root / "INDEX.md"
    if args.check:
        if not target.exists():
            print("INDEX.md is missing; run build_index.py", file=sys.stderr)
            return 1
        if body(target.read_text()) != body(fresh):
            print("INDEX.md is stale; run build_index.py", file=sys.stderr)
            return 1
        print("INDEX.md is current")
        return 0

    target.write_text(fresh, encoding="utf-8")
    print(f"wrote {target} ({len(fresh)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
