#!/usr/bin/env python3
"""Generate the index page under each entity folder.

Entity files are not browsable as a flat list. These rollups group by the
primary axes: domain, dimension, stage, or type.

Generated rather than written by hand. CI keeps it current.

Usage:
    build_rollups.py <repo>            write the rollups
    build_rollups.py <repo> --check    exit 1 if they are out of date
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    print("needs PyYAML:  pip install pyyaml", file=sys.stderr)
    raise SystemExit(2)

BANNER = "<!-- Generated by scripts/build_rollups.py — edits here will be overwritten. -->"


def load(folder: Path) -> dict[str, dict]:
    out = {}
    for path in sorted(folder.glob("*.md")):
        if path.name.lower() in {"readme.md", "index.md"}:
            continue
        text = path.read_text(encoding="utf-8")
        data = {}
        if text.startswith("---"):
            try:
                data = yaml.safe_load(text.split("---", 2)[1]) or {}
            except yaml.YAMLError:
                data = {}
        out[path.stem] = data if isinstance(data, dict) else {}
    return out


def label(slug: str, entities: dict[str, dict]) -> str:
    return (entities.get(slug) or {}).get("name") or slug.replace("-", " ").title()


def link(folder: str, slug: str, entities: dict[str, dict]) -> str:
    return f"[{label(slug, entities)}]({folder}/{slug}.md)"


def section(title: str, rows: list[str]) -> list[str]:
    if not rows:
        return []
    return [f"\n## {title}\n", *rows]


# ------------------------------------------------------------- AI Diffusion Model


def roll_pathways(pathways: dict[str, dict], units: dict[str, dict]) -> str:
    unit_counts: dict[str, int] = defaultdict(int)
    for u_data in units.values():
        p_slug = u_data.get("pathway")
        if p_slug:
            unit_counts[p_slug] += 1

    by_domain: dict[str, list[str]] = defaultdict(list)
    for slug, data in pathways.items():
        domain = data.get("domain") or "General / Cross-Domain"
        by_domain[domain].append(slug)

    lines = [f"# AI Diffusion Pathways\n", BANNER, f"\n{len(pathways)} AI diffusion pathways."]
    for domain in sorted(by_domain):
        rows = []
        for slug in sorted(by_domain[domain], key=lambda s: label(s, pathways).lower()):
            data = pathways[slug]
            stage = data.get("stage_reached") or "Stage not recorded"
            pop = data.get("population_scale") or data.get("population_served") or ""
            pop_str = f" · Pop: {pop}" if pop else ""
            n_units = unit_counts.get(slug, 0)
            u_str = f" · {n_units} unit{'s' if n_units != 1 else ''}" if n_units else ""
            rows.append(f"- {link('pathways', slug, pathways)} — {stage}{pop_str}{u_str}")
        lines += section(f"{domain} ({len(by_domain[domain])})", rows)
    return "\n".join(lines) + "\n"


def roll_units(units: dict[str, dict], pathways: dict[str, dict]) -> str:
    by_dim: dict[str, list[str]] = defaultdict(list)
    for slug, data in units.items():
        dim = data.get("dimension") or "General"
        by_dim[dim].append(slug)

    lines = [f"# Micro-Innovation Units\n", BANNER, f"\n{len(units)} reusable micro-innovation units."]
    for dim in sorted(by_dim):
        rows = []
        for slug in sorted(by_dim[dim], key=lambda s: label(s, units).lower()):
            data = units[slug]
            p_slug = data.get("pathway")
            p_str = f" — Pathway: {link('pathways', p_slug, pathways)}" if p_slug and p_slug in pathways else ""
            u_type = data.get("unit_type") or ""
            stage = data.get("stage") or ""
            meta_bits = [b for b in [stage, u_type] if b]
            meta_str = f" ({' · '.join(meta_bits)})" if meta_bits else ""
            rows.append(f"- {link('units', slug, units)}{p_str}{meta_str}")
        lines += section(f"{dim} ({len(by_dim[dim])})", rows)
    return "\n".join(lines) + "\n"


def roll_toolkits(toolkits: dict[str, dict], pathways: dict[str, dict]) -> str:
    by_type: dict[str, list[str]] = defaultdict(list)
    for slug, data in toolkits.items():
        t_type = data.get("toolkit_type") or "General"
        by_type[t_type].append(slug)

    lines = [f"# Toolkits & Reusable Assets\n", BANNER, f"\n{len(toolkits)} toolkits and reusable assets."]
    for t_type in sorted(by_type):
        rows = []
        for slug in sorted(by_type[t_type], key=lambda s: label(s, toolkits).lower()):
            data = toolkits[slug]
            dim = data.get("dimension") or ""
            dim_str = f" — Dimension: {dim}" if dim else ""
            lic = data.get("license") or ""
            lic_str = f" · License: {lic}" if lic else ""
            rows.append(f"- {link('toolkits', slug, toolkits)}{dim_str}{lic_str}")
        lines += section(f"{t_type.title()} ({len(by_type[t_type])})", rows)
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------- Default Entity Model


def roll_organizations(orgs, projects) -> str:
    counts: dict[str, int] = defaultdict(int)
    for data in projects.values():
        for org in data.get("organizations") or []:
            if isinstance(org, dict) and org.get("role") == "customer" and org.get("slug"):
                counts[org["slug"]] += 1

    by_sector: dict[str, list[str]] = defaultdict(list)
    for slug in orgs:
        by_sector[(orgs[slug].get("broad_sector") or "Unclassified")].append(slug)

    lines = [f"# Organizations\n", BANNER, f"\n{len(orgs)} organizations."]
    for sector in sorted(by_sector):
        rows = []
        for slug in sorted(by_sector[sector], key=lambda s: label(s, orgs).lower()):
            n = counts.get(slug, 0)
            suffix = f" — {n} engagement{'s' if n != 1 else ''}" if n else ""
            rows.append(f"- {link('organizations', slug, orgs)}{suffix}")
        lines += section(f"{sector} ({len(by_sector[sector])})", rows)
    return "\n".join(lines) + "\n"


def roll_projects(projects, orgs) -> str:
    by_stage: dict[str, list[str]] = defaultdict(list)
    for slug, data in projects.items():
        by_stage[(data.get("engagement_stage") or "Stage not recorded")].append(slug)

    lines = [f"# Projects\n", BANNER, f"\n{len(projects)} engagements."]
    order = ["Production Scale", "Pilot", "POC (Proof of Concept)", "Stage not recorded"]
    for stage in order + [s for s in sorted(by_stage) if s not in order]:
        if stage not in by_stage:
            continue
        rows = []
        for slug in sorted(by_stage[stage], key=lambda s: label(s, projects).lower()):
            customers = [
                link("organizations", o["slug"], orgs)
                for o in (projects[slug].get("organizations") or [])
                if isinstance(o, dict) and o.get("role") == "customer" and o.get("slug")
            ]
            who = f" — {', '.join(customers)}" if customers else ""
            rows.append(f"- {link('projects', slug, projects)}{who}")
        lines += section(f"{stage} ({len(by_stage[stage])})", rows)
    return "\n".join(lines) + "\n"


def roll_people(people, orgs) -> str:
    by_org: dict[str, list[str]] = defaultdict(list)
    for slug, data in people.items():
        affiliations = [
            a["organization"] for a in (data.get("affiliations") or [])
            if isinstance(a, dict) and a.get("organization") and a.get("status") != "past"
        ]
        for org in affiliations or ["No current affiliation"]:
            by_org[org].append(slug)

    lines = [f"# People\n", BANNER, f"\n{len(people)} people."]
    for org in sorted(by_org, key=lambda o: (label(o, orgs) if o in orgs else o).lower()):
        heading = label(org, orgs) if org in orgs else org
        rows = []
        for slug in sorted(by_org[org], key=lambda s: label(s, people).lower()):
            roles = [
                a.get("role") for a in (people[slug].get("affiliations") or [])
                if isinstance(a, dict) and a.get("organization") == org and a.get("role")
            ]
            rows.append(f"- {link('people', slug, people)}" + (f" — {roles[0]}" if roles else ""))
        lines += section(f"{heading} ({len(by_org[org])})", rows)
    return "\n".join(lines) + "\n"


def roll_products(products, projects) -> str:
    used: dict[str, int] = defaultdict(int)
    for data in projects.values():
        for item in (data.get("products_leveraged") or []) + (data.get("reusable_components") or []):
            if isinstance(item, str):
                used[item] += 1

    lines = [f"# Products\n", BANNER,
             f"\n{len(products)} products — artifacts reused beyond the engagement that built them."]
    rows = []
    for slug in sorted(products, key=lambda s: label(s, products).lower()):
        n = used.get(slug, 0)
        bits = [b for b in [products[slug].get("license"), products[slug].get("funding_model")] if b]
        detail = f" — used in {n} engagement{'s' if n != 1 else ''}" if n else ""
        detail += f" · {' · '.join(bits)}" if bits else ""
        rows.append(f"- {link('products', slug, products)}{detail}")
    lines += section("All products", rows)
    return "\n".join(lines) + "\n"


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        return 0
    if len(args) != 1:
        print(__doc__)
        return 1
    repo = Path(args[0])

    candidates = {}
    # AI Diffusion custom entities
    if (repo / "pathways").is_dir():
        pathways = load(repo / "pathways")
        units = load(repo / "units") if (repo / "units").is_dir() else {}
        candidates["pathways.md"] = lambda: roll_pathways(pathways, units)
    if (repo / "units").is_dir():
        units = load(repo / "units")
        pathways = load(repo / "pathways") if (repo / "pathways").is_dir() else {}
        candidates["units.md"] = lambda: roll_units(units, pathways)
    if (repo / "toolkits").is_dir():
        toolkits = load(repo / "toolkits")
        pathways = load(repo / "pathways") if (repo / "pathways").is_dir() else {}
        candidates["toolkits.md"] = lambda: roll_toolkits(toolkits, pathways)

    # Standard model entities
    if (repo / "organizations").is_dir():
        orgs = load(repo / "organizations")
        projects = load(repo / "projects") if (repo / "projects").is_dir() else {}
        candidates["organizations.md"] = lambda: roll_organizations(orgs, projects)
    if (repo / "projects").is_dir():
        projects = load(repo / "projects")
        orgs = load(repo / "organizations") if (repo / "organizations").is_dir() else {}
        candidates["projects.md"] = lambda: roll_projects(projects, orgs)
    if (repo / "people").is_dir():
        people = load(repo / "people")
        orgs = load(repo / "organizations") if (repo / "organizations").is_dir() else {}
        candidates["people.md"] = lambda: roll_people(people, orgs)
    if (repo / "products").is_dir():
        products = load(repo / "products")
        projects = load(repo / "projects") if (repo / "projects").is_dir() else {}
        candidates["products.md"] = lambda: roll_products(products, projects)

    pages = {name: render_fn() for name, render_fn in candidates.items()}
    if not pages:
        print(f"{repo} has no recognized entity folders — nothing to roll up.", file=sys.stderr)
        return 0

    stale = []
    for name, content in pages.items():
        path = repo / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print("rollups are out of date: " + ", ".join(stale), file=sys.stderr)
            print("run:  python3 scripts/build_rollups.py .", file=sys.stderr)
            return 1
        print("rollups are current")
        return 0

    print(f"wrote {len(pages)} rollups")
    for name in pages:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
