#!/usr/bin/env python3
"""Generate the monthly activity digests from create-only entry files.

The activity log is an append-only ledger, and appending used to mean
rewriting the whole monthly file — which, through a connector that can only
replace entire blobs, corrupted `activities/2026-08.md` three times in one
month as it grew toward the model's output ceiling. Since 2026-09 the write
is create-only: every logging event adds one small file under
`activities/entries/<YYYY-MM>/`, and the monthly file people actually read
is generated from them, exactly like rollups and backlinks.

    build_activity_log.py <wiki-root>            regenerate the digests
    build_activity_log.py <wiki-root> --check    report staleness, write nothing

Rules this script enforces rather than trusts:

- **A month with no entries directory is frozen history.** Monthly files
  from before the cutover are hand-shaped and never touched. A month that
  has BOTH a hand-shaped file (no generated marker) and an entries
  directory is a conflict a human must resolve; the script refuses.
- **A line it did not generate is rescued, never dropped.** A writer on an
  old skill version may still append to the generated digest directly;
  regeneration folds any such line into a rescue entry file first, so the
  ledger loses nothing however stale the writer.

Pure standard library.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

MARKER = "Generated by build_activity_log.py"
MONTH_RE = re.compile(r"^\d{4}-\d{2}$")
MONTH_NAMES = ["January", "February", "March", "April", "May", "June", "July",
               "August", "September", "October", "November", "December"]


def month_title(month: str) -> str:
    year, mm = month.split("-")
    return f"{MONTH_NAMES[int(mm) - 1]} {year}"


def header(month: str) -> str:
    return (
        f"# Activity Log — {month_title(month)}\n"
        "\n"
        f"{MARKER} — do not edit this file. One entry file per logged\n"
        f"event lives in `activities/entries/{month}/`; write a new file\n"
        "there, never a line here. This page is regenerated by CI and by\n"
        "`build_activity_log.py`.\n"
        "\n"
        "Format: `- {YYYY-MM-DD}: [{entity type}] {entity name} — "
        "{one-line summary}`\n"
    )


def entry_files(entries_dir: Path) -> list[Path]:
    return sorted(p for p in entries_dir.glob("*.md")
                  if p.name.lower() != "readme.md")


def render(month: str, entries_dir: Path) -> str:
    blocks = []
    for path in entry_files(entries_dir):
        text = path.read_text(encoding="utf-8", errors="ignore").strip()
        if text:
            blocks.append(text)
    return header(month) + "\n" + "\n".join(blocks) + ("\n" if blocks else "")


def content_lines(text: str) -> set[str]:
    """The ledger lines of a digest — everything that looks like an entry."""
    return {line.strip() for line in text.splitlines()
            if line.strip().startswith("- ")
            and not line.strip().startswith("- {")}  # the format line


def rescue(month: str, entries_dir: Path, existing: str, generated: str) -> Path | None:
    """Fold lines someone appended to the digest into an entry file."""
    stray = content_lines(existing) - content_lines(generated)
    if not stray:
        return None
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    target = entries_dir / f"{stamp}-rescued-r1.md"
    suffix = 1
    while target.exists():
        suffix += 1
        target = entries_dir / f"{stamp}-rescued-r{suffix}.md"
    target.write_text("\n".join(sorted(stray)) + "\n", encoding="utf-8")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("root", help="wiki repository root")
    parser.add_argument("--check", action="store_true",
                        help="report stale digests and exit non-zero; never write")
    args = parser.parse_args()

    root = Path(args.root)
    entries_root = root / "activities" / "entries"
    if not (root / "CONVENTIONS.md").exists():
        print(f"{root} does not look like a wiki (no CONVENTIONS.md)", file=sys.stderr)
        return 2
    if not entries_root.is_dir():
        print("no activities/entries/ — nothing to generate")
        return 0

    stale, wrote = [], []
    for entries_dir in sorted(p for p in entries_root.iterdir() if p.is_dir()):
        month = entries_dir.name
        if not MONTH_RE.match(month):
            print(f"skipping activities/entries/{month} — not a YYYY-MM directory",
                  file=sys.stderr)
            continue
        digest = root / "activities" / f"{month}.md"
        existing = digest.read_text(encoding="utf-8", errors="ignore") if digest.exists() else ""

        if existing and MARKER not in existing:
            print(f"REFUSING {digest.name}: it is hand-shaped history, but "
                  f"entries/{month}/ exists. A human must decide which wins.",
                  file=sys.stderr)
            return 1

        generated = render(month, entries_dir)
        if args.check:
            if existing != generated and content_lines(existing) != content_lines(generated):
                stale.append(digest.name)
            continue

        rescued = rescue(month, entries_dir, existing, generated)
        if rescued:
            print(f"rescued stray digest line(s) into {rescued.relative_to(root)}")
            generated = render(month, entries_dir)
        if existing != generated:
            digest.write_text(generated, encoding="utf-8")
            wrote.append(digest.name)

    if args.check:
        if stale:
            print("stale digest(s): " + ", ".join(stale) +
                  " — run build_activity_log.py", file=sys.stderr)
            return 1
        print("activity digests are current")
        return 0

    print(f"regenerated {len(wrote)} digest(s)" + (": " + ", ".join(wrote) if wrote else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
